Feature/fltr 588
UnitedTraders/docusign-flutter pull request #1
Opened 2021-11-26 08:25 UTC by werewolfvit

2021-11-28 07:47 UTC, akurdyukov requested changes

2021-11-28 07:47 UTC, akurdyukov commented on CHANGELOG.md
> +* TODO: Describe initial release.
Can you write something here pls?

2021-11-28 07:47 UTC, akurdyukov commented on LICENSE
> +TODO: Add your license here.
Suppose we should use MIT license

2021-11-28 07:47 UTC, akurdyukov commented on example/android/app/local.properties
> +## This file must *NOT* be checked into Version Control Systems,
this file should be removed, I guess

2021-11-28 07:47 UTC, akurdyukov commented on ios/docusign_flutter.podspec
> +  s.author           = { 'Your Company' => 'email@example.com' }
I guess we should fill this

2021-11-29 07:56 UTC, vadlit requested changes

2021-11-29 07:56 UTC, vadlit commented on .idea/.gitignore
> +# Default ignored files
Please add .idea folder in gitignore

2021-11-29 07:56 UTC, vadlit commented on android/.idea/.gitignore
> +# Default ignored files
.idea should be in gitignore

2021-11-29 07:56 UTC, vadlit commented on android/src/main/kotlin/com/unitedtraders/mobile/docusign_flutter/DocusignFlutterPlugin.kt
> +    // TODO необходимо решить проблему с запуском вне Activity, т.к. само создание Intent от нас скрыто - это проблема.
So signing doesn't work right now?

2021-11-30 09:49 UTC, werewolfvit commented on android/src/main/kotlin/com/unitedtraders/mobile/docusign_flutter/DocusignFlutterPlugin.kt
> +    // TODO необходимо решить проблему с запуском вне Activity, т.к. само создание Intent от нас скрыто - это проблема.
fixed

2021-11-30 09:49 UTC, werewolfvit commented on android/.idea/.gitignore
> +# Default ignored files
done

2021-11-30 09:49 UTC, werewolfvit commented on .idea/.gitignore
> +# Default ignored files
done

2021-11-30 09:50 UTC, werewolfvit commented on ios/docusign_flutter.podspec
> +  s.author           = { 'Your Company' => 'email@example.com' }
done, please check

2021-11-30 09:50 UTC, werewolfvit commented on example/android/app/local.properties
> +## This file must *NOT* be checked into Version Control Systems,
done

2021-11-30 09:50 UTC, werewolfvit commented on LICENSE
> +TODO: Add your license here.
done

2021-11-30 09:51 UTC, werewolfvit commented on CHANGELOG.md
> +* TODO: Describe initial release.
done

2021-12-01 07:48 UTC, vadlit approved these changes

2021-12-01 09:21 UTC, Malarg approved these changes

2021-12-01 09:47 UTC, akurdyukov commented on example/README.md
> +## Getting Started
Pls delete this if it's not really relevant

2021-12-01 10:02 UTC, merged